
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FileLogger.java
//  @ Date : 2018. 10. 15.
//  @ Author : 
//
//




public class FileLogger implements Observer {
	String fileName;
	public FileLogger(String fileName) {
		this.fileName = fileName;
	}

	@Override
	public void report(Observable observable) {
		FileWriter file_writer;
		try {
			file_writer = new FileWriter(fileName, true);
			BufferedWriter writer = new BufferedWriter(file_writer);
			
			writer.write(observable.toString()+'\n');
			writer.flush();
			writer.close();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
}
