//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Observer.java
//  @ Date : 2018. 10. 15.
//  @ Author : 
//
//




public interface Observer {
	public void report(Observable observable);
}
