//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : StdOutLogger.java
//  @ Date : 2018. 10. 15.
//  @ Author : 
//
//




public class StdOutLogger implements Observer {

	@Override
	public void report(Observable observable) {
		System.out.println(observable.toString());
	}
}
